/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : MediaInfo
 #	author : miyako
 #	2015/08/29
 #
 # --------------------------------------------------------------------------------*/

#include "MediaInfo.h"
#include "MediaInfo/MediaInfo_Internal.h"

#define STREAM_BUFFER_SIZE 4096

#define MediaInfo_Inform_HTML (1)
#define MediaInfo_Inform_CSV (2)
#define MediaInfo_Inform_XML (3)

// --- MediaInfo
void MediaInfo(sLONG_PTR *pResult, PackagePtr pParams);
