/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-MediaInfo.h
 #	source generated by 4D Plugin Wizard
 #	Project : MediaInfo
 #	author : miyako
 #	2022/05/12
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MEDIAINFO_H
#define PLUGIN_MEDIAINFO_H

#include "4DPluginAPI.h"

#include "MediaInfo.h"
#include "MediaInfo/MediaInfo_Internal.h"

#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#if VERSIONMAC
#define CPathString CUTF8String
#define CPathOpen fopen
#define CPathSeek fseek
#define CPathTell ftell
#define CPathAppend "ab"
#define CPathCreate "wb"
#define CPathRead "rb"
#else
#include <Shlobj.h>
#define CPathString CUTF16String
#define CPathOpen _wfopen
#define CPathSeek _fseeki64
#define CPathTell _ftelli64
#define CPathAppend L"ab"
#define CPathCreate L"wb"
#define CPathRead L"rb"
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <io.h>
#include <stdio.h>
#endif

#define STREAM_BUFFER_SIZE 4096

#define MediaInfo_Inform_HTML (1)
#define MediaInfo_Inform_CSV (2)
#define MediaInfo_Inform_XML (3)
#define MediaInfo_Inform_JSON (4)
#define MediaInfo_Inform_OLDXML (5)
#define MediaInfo_Inform_EBUCore (6)
#define MediaInfo_Inform_PBCore (7)
#define MediaInfo_Inform_PBCore2 (8)
#define MediaInfo_Inform_EBUCore_JSON (9)

#if VERSIONWIN
#include <time.h>
#endif

#pragma mark -

static void MediaInfo(PA_PluginParameters params);
static void MediaInfoFile(PA_PluginParameters params);

#endif /* PLUGIN_MEDIAINFO_H */
